### ISSUE TITLE
C# support

### ISSUE THREAD

**Issue by mattc-eostar** [BayesWitnesses/m2cgen#101]
Is there a roadmap for converting models to C# code? I work at a Microsoft shop and this would be great to use instead of ML.NET since this is so much more lightweight. Thanks!

**Comment by izeigerman** [comment]
Hey @mattc-eostar! 

We didn't have a roadmap for C# support since it wasn't exactly clear whether there is a demand for it. Now, however, you've provided a clear indication that there is one :) Thank you for considering using this project!

I personally have never worked with C# before and to the best of my knowledge nobody from this project team have any experience with it either. Would you perhaps consider contributing it? I believe you can take Java/JS as an example and replicate it with C# constructs. People who were not familiar with the codebase at all have successfully contributed Golang and JS support in the past. You can look at their commits as a reference too. And of course we're always here to help.

Otherwise I'll definitely work on it at some point but unfortunately can't commit to any particular date.

**Comment by mattc-eostar** [comment]
Not a problem, I will see what I can do. Thank you for the quick response. This wouldn't be a show-stopper for us by any means, but a neat tool in our toolbox.
I would have to guess that the code would look extremely similar to the Java output. I will be AFK for the next two weeks, so it may have to wait until after that unless someone else feels compelled to do it.
