### ISSUE TITLE
Planned support for raw xgb.Booster.model and raw lgb.Booster.model?

### ISSUE THREAD

**Issue by Jie-Yuan** [BayesWitnesses/m2cgen#164]
Planned support for raw xgb.Booster.model and raw lgb.Booster.model?

**Comment by izeigerman** [comment]
Hey @Jie-Yuan ! Thanks for reporting this.
We already have an open issue for this: https://github.com/BayesWitnesses/m2cgen/issues/99.
And even a PR fixing it: https://github.com/BayesWitnesses/m2cgen/pull/104. Although the PR is somewhat stale. 
At this point plans on supporting XGBoost and LightGBM Booster objects are unclear. Though since more and more people ask for it, we should consider implement it soon.
Meanwhile you can use the following workaround: https://github.com/BayesWitnesses/m2cgen/issues/90#issuecomment-492715623. 
Closing this issue as duplicate, please feel free to comment in https://github.com/BayesWitnesses/m2cgen/issues/99.
