### ISSUE TITLE
Will there be an R interface

### ISSUE THREAD

**Issue by xianglinZ** [BayesWitnesses/m2cgen#189]
Hello, do you plan to provide an interface for the R language, I think that the R language is comparable to Python in some aspects, can you give R an interface?

**Comment by izeigerman** [comment]
Hey @xianglinZ. Thanks for reaching out! 

As of this moment there are no plans to support models built with R.

**Comment by xianglinZ** [comment]
Thank you for your reply. As a co-user of R and Python, I hope that you can provide an interface for R, thanks

**Comment by xianglinZ** [comment]
Thank you for your reply. As a co-user of R and Python, I hope that you can provide an interface for R, thanks

**Comment by StrikerRUS** [comment]
@xianglinZ Hey!

Can you please clarify your feature request? Do you want to transpile R-objects (e.g. from `ranger` package) into native code or to use current `m2cgen` functionality from R language? If latter, can `reticulate` package solve your issue?

Also, I'd like to see any examples of 
> I think that the R language is comparable to Python in some aspects,

**Comment by xianglinZ** [comment]
Sorry, my English level is average, there may be some misunderstandings.
1.reticulate can solve many problems, but of course not as good as the native R package;
2. When I say that R and Python are comparable, I mean that in data science, R and Python are very popular and have many similarities in function;
3. Thank you very much for your reply. Because R is used more, I want to get the same support as Python, but now it seems that Python seems to be more popular and more supported than R;
Thank you for your reply, and I wish you all the best!

**Comment by StrikerRUS** [comment]
@izeigerman Do you know R? I'm asking with the aim to understand whether it makes sense to keep this issue open or not. In other words, is it possible in principle to address the following

> Because R is used more, I want to get the same support as Python, ...


In my understandings, it's better to create another project (repo) for a similar R transpiler. Because I can't imagine how to maintain Python and R codebase at the same time in one repo.

**Comment by izeigerman** [comment]
@StrikerRUS Unfortunately I have literally zero knowledge of R. At the same time I'm not convinced that it's possible to reuse any existing code as is in R environment. You're right saying that the whole separate implementation is required to support it. 

> In my understandings, it's better to create another project (repo) for a similar R transpiler

Yeah, pretty much. I suggest we close this issue, since it won't be addressed as part of this project anyway.
