### ISSUE TITLE
PCA 

### ISSUE THREAD

**Issue by MilanCugur** [BayesWitnesses/m2cgen#270]
Could you support PCA transformation (as it's just a matrix multiplication when the algorithm is fitted)?

**Comment by izeigerman** [comment]
Hey @MilanCugur! Thanks for reporting this issue.

Let me clarify your request. Do you suggest we should introduce support for PCA in a form of an estimator (model) or in a form of a pre-processing step? 

If the former, then I don't think it's going to be that straightforward since the current design assumes that the generated code always returns a scalar. The output of the PCA is vector.

If the latter then please see my thoughts around supporting arbitrary pre-processing steps in the comment - 
https://github.com/BayesWitnesses/m2cgen/issues/141#issuecomment-569853439

**Comment by MilanCugur** [comment]
Thank you for the response.
