### ISSUE TITLE
NotImplementedError: Model 'numpy_ndarray' is not supported

### ISSUE THREAD

**Issue by yarix** [BayesWitnesses/m2cgen#287]
while running `m2cgen --language java ModelOnline.joblib > model1.java` got error `NotImplementedError: Model 'numpy_ndarray' is not supported`. Are there plans to support it?

**Comment by izeigerman** [comment]
Hey @yarix thanks for reporting this.
Can you please share more details around what the `ModelOnline.joblib` file actually is? It seems like it's a serialized Numpy Array object and not the actual model object. 
Please note that `m2cgen` expects a scikit-learn/XGBoost/LightGBM model serialized in pickle format.

**Comment by yarix** [comment]
the joblib is a dump of the model i got from my DataScienceTeam. it was probably created with [sklearn joblib](https://scikit-learn.org/stable/modules/model_persistence.html)
```
>>> from joblib import dump
>>> dump(model, 'filename.joblib') 
```  

i will try with pkl dump and will update the ticket

thanks

**Comment by yarix** [comment]
hi
i got a newer pkl dump, and now the error is `NotImplementedError: Model 'sklearn_Pipeline' is not supported`.
i will close this issue, let me know if i need to open a new issue for `sklearn_Pipeline`

**Comment by izeigerman** [comment]
Hey @yarix! 
`m2cgen` doesn't support Scikit-learn pipelines since besides the model itself it also contains transformation steps. This library doesn't cover the preprocessing piece and only takes care of the model itself. 
In case the scikit-learn `Pipeline`s the estimator (model) is usually the very last step, so you should try and extract the last item of the pipeline and then pass it into `m2cgen`.

**Comment by yarix** [comment]
thanks will give it another try with the model only.
